// lib/translations.ts
/**
 * Translations for AI Supply Chain Risk Prediction Demo
 * Supports English and Traditional Chinese
 */

export type Language = 'en' | 'zh';

interface Translations {
  // Header
  appTitle: string;
  appSubtitle: string;
  lastUpdate: string;
  
  // Tabs
  overview: string;
  batteryHealth: string;
  environmentalMonitoring: string;
  routeSecurity: string;
  aiAssistant: string;
  co2Tab: string;
  reportGeneration: string;
  
  // Overview
  overallRisk: string;
  criticalAlerts: string;
  avgBatteryHealth: string;
  needsReplacement: string;
  environmentalAnomalies: string;
  criticalAnomalies: string;
  routeEvents: string;
  tamperAlerts: string;
  
  // Project Names
  projectA: string;
  projectADesc: string;
  projectB: string;
  projectBDesc: string;
  projectC: string;
  projectCDesc: string;
  projectD: string;
  projectDDesc: string;
  
  // Common
  highRisk: string;
  normal: string;
  devices: string;
  alerts: string;
  events: string;
  severity: string;
  critical: string;
  high: string;
  medium: string;
  low: string;
  info: string;
  
  // Battery
  totalDevices: string;
  immediateReplacement: string;
  avgRUL: string;
  days: string;
  batteryStatus: string;
  capacity: string;
  voltage: string;
  temperature: string;
  chargeCycles: string;
  trend: string;
  improving: string;
  stable: string;
  degrading: string;
  
  // Environmental
  totalAnomalies: string;
  temperatureAnomalies: string;
  humidityAnomalies: string;
  environmentalAlerts: string;
  
  // Route
  totalEvents: string;
  routeDeviations: string;
  tamperEvents: string;
  geofenceViolations: string;
  routeSecurityEvents: string;
  
  // NLQ
  nlqTitle: string;
  nlqPlaceholder: string;
  send: string;
  analyzing: string;
  greeting: string;
  
  // Report
  reportTitle: string;
  generateReport: string;
  generating: string;
  noReport: string;
  clickToGenerate: string;
  
  // CO2 & Sustainability
  co2Reduction: string;
  co2Saved: string;
  co2Equivalent: string;
  treesEquivalent: string;
  carbonFootprint: string;
  
  // Footer
  footerTitle: string;
  footerProjects: string;
  footerCopyright: string;
  
  // Trend indicators
  trendUp: string;
  trendDown: string;
  trendStable: string;
  
  // Device names
  cargoTracker: string;
  smartTote: string;
  envSensor: string;
  
  // Mock data descriptions (Environmental)
  coffeeTemp: string;
  pharmaHumidity: string;
  electronicsVibration: string;
  
  // Mock data descriptions (Route)
  routeDeviation: string;
  unauthorizedAccess: string;
  unexpectedStop: string;
  leftAuthorizedZone: string;
  
  // Location names
  taipeiZhongzheng: string;
  newTaipeiZhonghe: string;
  taipeiSongshan: string;
  nangangLogistics: string;
  
  // NLQ Sample questions
  sampleQuestion1: string;
  sampleQuestion2: string;
  sampleQuestion3: string;
  tryAsking: string;
  
  // NLQ Responses
  batteryStatusReport: string;
  needsImmediateReplacement: string;
  needsScheduling: string;
  recommendation: string;
  priorityReplace: string;
  todayAnomaliesReport: string;
  environmentalAnomaliesTitle: string;
  routeEventsTitle: string;
  investigate: string;
  routeAnalysisReport: string;
  currentStatus: string;
  inTransit: string;
  routeCompliance: string;
  detectedEvents: string;
  checkDriver: string;
  updateRoute: string;
  thankYouInquiry: string;
  canProvideAnalysis: string;
  batteryHealthQuery: string;
  environmentalMonitoringQuery: string;
  routeSecurityQuery: string;
  whatCanIHelp: string;
  
  // Report generation
  reportDate: string;
  reportId: string;
  executiveSummary: string;
  warning: string;
  criticalEventsNeedAttention: string;
  normalOperation: string;
  noCriticalAlerts: string;
  keyIndicators: string;
  indicator: string;
  value: string;
  overallRiskScore: string;
  environmentalAnomalyCount: string;
  routeEventCount: string;
  batteryHealthAnalysis: string;
  environmentalMonitoringTitle: string;
  routeSecurityTitle: string;
  recommendedActions: string;
  replaceKeyBatteries: string;
  investigateEnvAnomalies: string;
  investigateTamper: string;
  continueMonitoring: string;
  maintainEnvMonitoring: string;
  continueRouteMonitoring: string;
  autoGeneratedReport: string;
  
  // Table/List headers
  deviceName: string;
  deviceId: string;
  valueLabel: string;
  threshold: string;
  location: string;
  description: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    // Header
    appTitle: 'AI Smart Supply Chain Risk Prediction',
    appSubtitle: 'AI Application Advancement Program Demo',
    lastUpdate: 'Last Update',
    
    // Tabs
    overview: 'Overview',
    batteryHealth: 'Battery Health',
    environmentalMonitoring: 'Environmental',
    routeSecurity: 'Route Security',
    aiAssistant: 'AI Assistant',
    co2Tab: 'CO₂ Impact',
    reportGeneration: 'Reports',
    
    // Overview
    overallRisk: 'Overall Risk Score',
    criticalAlerts: 'critical alerts',
    avgBatteryHealth: 'Avg Battery Health',
    needsReplacement: 'needs immediate replacement',
    environmentalAnomalies: 'Environmental Anomalies',
    criticalAnomalies: 'critical anomalies',
    routeEvents: 'Route Events',
    tamperAlerts: 'tamper alerts',
    
    // Project Names
    projectA: 'Project A: BHI/RUL Prediction',
    projectADesc: 'Battery Health & Lifetime Prediction',
    projectB: 'Project B: Natural Language Query',
    projectBDesc: 'AI Assistant Real-time Response',
    projectC: 'Project C: Environmental Anomaly Detection',
    projectCDesc: 'Temperature, Humidity, Vibration Monitoring',
    projectD: 'Project D: Route & Theft Detection',
    projectDDesc: 'Smart TOTE Security Monitoring',
    
    // Common
    highRisk: 'High Risk',
    normal: 'Normal',
    devices: 'devices',
    alerts: 'alerts',
    events: 'events',
    severity: 'Severity',
    critical: 'CRITICAL',
    high: 'HIGH',
    medium: 'MEDIUM',
    low: 'LOW',
    info: 'INFO',
    
    // Battery
    totalDevices: 'Total Devices',
    immediateReplacement: 'Needs Immediate Replacement',
    avgRUL: 'Average RUL',
    days: 'days',
    batteryStatus: 'Battery Health Status',
    capacity: 'Capacity',
    voltage: 'Voltage',
    temperature: 'Temperature',
    chargeCycles: 'Charge Cycles',
    trend: 'Trend',
    improving: 'Improving',
    stable: 'Stable',
    degrading: 'Degrading',
    
    // Environmental
    totalAnomalies: 'Total Anomalies',
    temperatureAnomalies: 'Temperature Anomalies',
    humidityAnomalies: 'Humidity Anomalies',
    environmentalAlerts: 'Environmental Alerts',
    
    // Route
    totalEvents: 'Total Events',
    routeDeviations: 'Route Deviations',
    tamperEvents: 'Tamper Events',
    geofenceViolations: 'Geofence Violations',
    routeSecurityEvents: 'Route Security Events',
    
    // NLQ
    nlqTitle: 'AI Natural Language Query',
    nlqPlaceholder: 'Type your question...',
    send: 'Send',
    analyzing: 'Analyzing...',
    greeting: 'Hello! I\'m your AI Supply Chain Risk Assistant. I can help you with:\n\n- Battery health status and lifetime predictions\n  • Try: "Show me battery trends" for interactive chart\n- Environmental anomaly detection results\n  • Try: "Show environment alert distribution" for pie chart\n- Route deviations and security events\n  • Try: "Show route event timeline" for severity analysis\n- Overall risk assessment\n\nHow can I help you?',
    
    // Report
    reportTitle: 'AI Event Report Generation',
    generateReport: 'Generate Report',
    generating: 'Generating...',
    noReport: 'No report generated yet',
    clickToGenerate: 'Click "Generate Report" to create an AI risk report',
    
    // CO2 & Sustainability
    co2Reduction: 'CO₂ Reduction',
    co2Saved: 'CO₂ Saved This Month',
    co2Equivalent: 'km driving avoided',
    treesEquivalent: 'trees planted equivalent',
    carbonFootprint: 'Carbon Footprint',
    
    // Footer
    footerTitle: 'AI Smart Supply Chain Risk Prediction System',
    footerProjects: 'Projects: A (BHI/RUL) | B (NLQ) | C (Environmental) | D (Route Security)',
    footerCopyright: '© 2025 AI Application Advancement Program · Demo Version',
    
    // Trend indicators
    trendUp: 'Up',
    trendDown: 'Down',
    trendStable: 'Stable',
    
    // Device names
    cargoTracker: 'Cargo Tracker',
    smartTote: 'Smart TOTE',
    envSensor: 'Environment Sensor',
    
    // Mock data descriptions (Environmental)
    coffeeTemp: 'Coffee shipment temperature exceeded - may affect quality',
    pharmaHumidity: 'Pharmaceutical shipment humidity abnormal - requires immediate inspection',
    electronicsVibration: 'Electronics shipment excessive vibration',
    
    // Mock data descriptions (Route)
    routeDeviation: 'Deviated 500m from planned route - recorded',
    unauthorizedAccess: 'Detected unauthorized opening - requires immediate confirmation',
    unexpectedStop: 'Unexpected stop for 12 minutes',
    leftAuthorizedZone: 'Left authorized zone',
    
    // Location names
    taipeiZhongzheng: 'Taipei Zhongzheng District',
    newTaipeiZhonghe: 'New Taipei Zhonghe District',
    taipeiSongshan: 'Taipei Songshan District',
    nangangLogistics: 'Nangang Logistics Center',
    
    // NLQ Sample questions
    sampleQuestion1: '"Which batteries need replacement?"',
    sampleQuestion2: '"Any anomalies today?"',
    sampleQuestion3: '"TOTE-001 route deviation status"',
    sampleQuestion4: '"Show me battery trends"',
    sampleQuestion5: '"Show environment alert distribution"',
    sampleQuestion6: '"Show route event timeline"',
    tryAsking: 'Try asking:',
    
    // NLQ Responses
    batteryStatusReport: '## Battery Health Status Report\n\nBased on latest data analysis:\n\n**Needs Immediate Replacement:**\n- 🔴 TOTE-001 (Smart TOTE #1): BHI 28%, RUL only 14 days remaining\n\n**Needs Scheduling Soon:**\n- 🟠 GPS-TRACKER-B2: BHI 62%, RUL 120 days\n- 🟡 TOTE-002: BHI 78%, RUL 340 days\n\n**Recommendation:** Prioritize replacing TOTE-001 battery to avoid operational disruption.',
    needsImmediateReplacement: 'Needs Immediate Replacement',
    needsScheduling: 'Needs Scheduling Soon',
    recommendation: 'Recommendation',
    priorityReplace: 'Prioritize replacing TOTE-001 battery to avoid operational disruption.',
    todayAnomaliesReport: '## Today\'s Anomaly Report\n\n### Environmental Anomalies (3)\n- 🔴 Pharmaceutical shipment humidity exceeded (85% > 60%)\n- 🟠 Coffee temperature abnormal (32°C > 25°C)\n- 🟡 Electronics excessive vibration\n\n### Route Events (4)\n- 🔴 TOTE-002 detected unauthorized opening\n- 🟠 TOTE-001 left authorized zone\n- 🟡 Route deviation 500m\n- 🔵 Unexpected stop 12 minutes\n\n**Recommendation:** Immediately investigate TOTE-002 tamper alert.',
    environmentalAnomaliesTitle: 'Environmental Anomalies',
    routeEventsTitle: 'Route Events',
    investigate: 'Investigate',
    routeAnalysisReport: '## TOTE-001 Route Analysis\n\n**Current Status:** In transit\n**Route Compliance:** 85%\n\n### Detected Events:\n1. ⚠️ Deviated 500m from planned route (1 hour ago)\n2. 🚨 Left authorized zone - Nangang Logistics Center (2 hours ago)\n\n### Recommendations:\n- Verify driver is following designated route\n- Consider updating route plan to cover common deviation points',
    currentStatus: 'Current Status',
    inTransit: 'In transit',
    routeCompliance: 'Route Compliance',
    detectedEvents: 'Detected Events',
    checkDriver: 'Verify driver is following designated route',
    updateRoute: 'Consider updating route plan to cover common deviation points',
    thankYouInquiry: 'Thank you for your inquiry!\n\nI can provide the following analysis:\n1. **Battery Health** - Query "which batteries need replacement"\n2. **Environmental Monitoring** - Query "any anomalies today"\n3. **Route Security** - Query "TOTE-001 route deviation status"\n\nWhat would you like to know?',
    canProvideAnalysis: 'I can provide the following analysis',
    batteryHealthQuery: 'Battery Health',
    environmentalMonitoringQuery: 'Environmental Monitoring',
    routeSecurityQuery: 'Route Security',
    whatCanIHelp: 'What would you like to know?',
    
    // Report generation
    reportDate: 'Report Date',
    reportId: 'Report ID',
    executiveSummary: 'Executive Summary',
    warning: 'Warning',
    criticalEventsNeedAttention: 'critical events require immediate attention.',
    normalOperation: 'Normal Operation',
    noCriticalAlerts: 'No critical alerts.',
    keyIndicators: 'Key Indicators',
    indicator: 'Indicator',
    value: 'Value',
    overallRiskScore: 'Overall Risk Score',
    environmentalAnomalyCount: 'Environmental Anomalies',
    routeEventCount: 'Route Events',
    batteryHealthAnalysis: 'Battery Health Analysis',
    environmentalMonitoringTitle: 'Environmental Monitoring',
    routeSecurityTitle: 'Route Security',
    recommendedActions: 'Recommended Actions',
    replaceKeyBatteries: '🔋 Immediately replace critical batteries',
    investigateEnvAnomalies: '🌡️ Investigate environmental anomaly causes',
    investigateTamper: '🔒 Investigate tamper alerts',
    continueMonitoring: '🔋 Continue monitoring battery health',
    maintainEnvMonitoring: '🌡️ Maintain environmental monitoring',
    continueRouteMonitoring: '🔒 Continue route monitoring',
    autoGeneratedReport: 'This report was automatically generated by AI',
    
    // Table/List headers
    deviceName: 'Device Name',
    deviceId: 'Device ID',
    valueLabel: 'Value',
    threshold: 'Threshold',
    location: 'Location',
    description: 'Description',
  },
  
  zh: {
    // Header
    appTitle: 'AI 智慧供應鏈風險預測',
    appSubtitle: 'AI應用躍昇計畫 Demo',
    lastUpdate: '最後更新',
    
    // Tabs
    overview: '總覽',
    batteryHealth: '電池健康',
    environmentalMonitoring: '環境監控',
    routeSecurity: '路線安全',
    aiAssistant: 'AI 助理',
    co2Tab: 'CO₂ 減量',
    reportGeneration: '報告生成',
    
    // Overview
    overallRisk: '整體風險分數',
    criticalAlerts: '個關鍵警報',
    avgBatteryHealth: '平均電池健康度',
    needsReplacement: '需立即更換',
    environmentalAnomalies: '環境異常',
    criticalAnomalies: '個關鍵異常',
    routeEvents: '路線事件',
    tamperAlerts: '個篡改警報',
    
    // Project Names
    projectA: '分項計畫 A: BHI/RUL 預測',
    projectADesc: '電池健康與壽命預測',
    projectB: '分項計畫 B: 自然語言查詢',
    projectBDesc: 'AI 助理即時回應',
    projectC: '分項計畫 C: 環境異常偵測',
    projectCDesc: '溫濕度、震動監控',
    projectD: '分項計畫 D: 路線防竊偵測',
    projectDDesc: 'Smart TOTE 安全監控',
    
    // Common
    highRisk: '高風險',
    normal: '正常',
    devices: '台設備',
    alerts: '個警報',
    events: '個事件',
    severity: '嚴重程度',
    critical: '關鍵',
    high: '高',
    medium: '中',
    low: '低',
    info: '資訊',
    
    // Battery
    totalDevices: '總設備數',
    immediateReplacement: '需立即更換',
    avgRUL: '平均 RUL',
    days: '天',
    batteryStatus: '電池健康狀態',
    capacity: '容量',
    voltage: '電壓',
    temperature: '溫度',
    chargeCycles: '充電循環',
    trend: '趨勢',
    improving: '改善中',
    stable: '穩定',
    degrading: '衰退中',
    
    // Environmental
    totalAnomalies: '總異常數',
    temperatureAnomalies: '溫度異常',
    humidityAnomalies: '濕度異常',
    environmentalAlerts: '環境異常警報',
    
    // Route
    totalEvents: '總事件數',
    routeDeviations: '路線偏離',
    tamperEvents: '篡改警報',
    geofenceViolations: '地理圍欄',
    routeSecurityEvents: '路線安全事件',
    
    // NLQ
    nlqTitle: 'AI 自然語言查詢',
    nlqPlaceholder: '輸入您的問題...',
    send: '發送',
    analyzing: '分析中...',
    greeting: '您好！我是 AI 供應鏈風險助理。我可以幫您查詢:\n\n- 電池健康狀態與壽命預測\n  • 試試看：「顯示電池趨勢」查看互動圖表\n- 環境異常偵測結果\n  • 試試看：「顯示環境警報分佈」查看圓餅圖\n- 路線偏離與安全事件\n  • 試試看：「顯示路線事件時間線」查看嚴重程度分析\n- 整體風險評估\n\n請問有什麼可以幫您的?',
    
    // Report
    reportTitle: 'AI 事件報告生成',
    generateReport: '生成報告',
    generating: '生成中...',
    noReport: '尚未生成報告',
    clickToGenerate: '點擊「生成報告」按鈕以創建 AI 風險報告',
    
    // CO2 & Sustainability
    co2Reduction: 'CO₂ 減量',
    co2Saved: '本月減少碳排',
    co2Equivalent: '公里駕駛減少',
    treesEquivalent: '相當於種樹',
    carbonFootprint: '碳足跡',
    
    // Footer
    footerTitle: 'AI 智慧供應鏈風險預測系統',
    footerProjects: '分項計畫: A (BHI/RUL) | B (NLQ) | C (環境異常) | D (路線防竊)',
    footerCopyright: '© 2025 AI應用躍昇計畫 · Demo 版本',
    
    // Trend indicators
    trendUp: '上升',
    trendDown: '下降',
    trendStable: '穩定',
    
    // Device names
    cargoTracker: '貨運追蹤器',
    smartTote: 'Smart TOTE',
    envSensor: '環境感測器',
    
    // Mock data descriptions (Environmental)
    coffeeTemp: '咖啡豆運輸溫度超標 - 可能影響品質',
    pharmaHumidity: '藥品運輸濕度異常 - 需立即檢查',
    electronicsVibration: '電子產品運輸震動過大',
    
    // Mock data descriptions (Route)
    routeDeviation: '偏離預定路線 500m - 已記錄',
    unauthorizedAccess: '偵測到非授權開啟 - 需立即確認',
    unexpectedStop: '未預期停留 12 分鐘',
    leftAuthorizedZone: '離開授權區域',
    
    // Location names
    taipeiZhongzheng: '台北市中正區',
    newTaipeiZhonghe: '新北市中和區',
    taipeiSongshan: '台北市松山區',
    nangangLogistics: '南港物流中心',
    
    // NLQ Sample questions
    sampleQuestion1: '「哪些電池需要更換?」',
    sampleQuestion2: '「今天有什麼異常?」',
    sampleQuestion3: '「TOTE-001 的路線偏離情況」',
    sampleQuestion4: '「顯示電池趨勢」',
    sampleQuestion5: '「顯示環境警報分佈」',
    sampleQuestion6: '「顯示路線事件時間線」',
    tryAsking: '試試問:',
    
    // NLQ Responses
    batteryStatusReport: '## 電池健康狀態報告\n\n根據最新數據分析:\n\n**需要立即更換:**\n- 🔴 TOTE-001 (Smart TOTE #1): BHI 28%, RUL 僅剩 14 天\n\n**需要近期排程:**\n- 🟠 GPS-TRACKER-B2: BHI 62%, RUL 120 天\n- 🟡 TOTE-002: BHI 78%, RUL 340 天\n\n**建議:** 優先更換 TOTE-001 的電池，以避免運營中斷。',
    needsImmediateReplacement: '需要立即更換',
    needsScheduling: '需要近期排程',
    recommendation: '建議',
    priorityReplace: '優先更換 TOTE-001 的電池，以避免運營中斷。',
    todayAnomaliesReport: '## 今日異常報告\n\n### 環境異常 (3 件)\n- 🔴 藥品運輸濕度超標 (85% > 60%)\n- 🟠 咖啡豆溫度異常 (32°C > 25°C)\n- 🟡 電子產品震動過大\n\n### 路線事件 (4 件)\n- 🔴 TOTE-002 偵測到非授權開啟\n- 🟠 TOTE-001 離開授權區域\n- 🟡 路線偏離 500m\n- 🔵 未預期停留 12 分鐘\n\n**建議:** 立即調查 TOTE-002 的篡改警報。',
    environmentalAnomaliesTitle: '環境異常',
    routeEventsTitle: '路線事件',
    investigate: '調查',
    routeAnalysisReport: '## TOTE-001 路線分析\n\n**當前狀態:** 運輸中\n**路線合規度:** 85%\n\n### 偵測事件:\n1. ⚠️ 偏離預定路線 500m (1 小時前)\n2. 🚨 離開授權區域 - 南港物流中心 (2 小時前)\n\n### 建議:\n- 確認司機是否按照指定路線行駛\n- 考慮更新路線規劃以涵蓋常見偏離點',
    currentStatus: '當前狀態',
    inTransit: '運輸中',
    routeCompliance: '路線合規度',
    detectedEvents: '偵測事件',
    checkDriver: '確認司機是否按照指定路線行駛',
    updateRoute: '考慮更新路線規劃以涵蓋常見偏離點',
    thankYouInquiry: '感謝您的詢問！\n\n我可以提供以下分析:\n1. **電池健康** - 查詢 "哪些電池需要更換"\n2. **環境監控** - 查詢 "今天有什麼異常"\n3. **路線安全** - 查詢 "TOTE-001 路線偏離情況"\n\n請告訴我您想了解什麼？',
    canProvideAnalysis: '我可以提供以下分析',
    batteryHealthQuery: '電池健康',
    environmentalMonitoringQuery: '環境監控',
    routeSecurityQuery: '路線安全',
    whatCanIHelp: '請告訴我您想了解什麼？',
    
    // Report generation
    reportDate: '報告日期',
    reportId: '報告 ID',
    executiveSummary: '執行摘要',
    warning: '警告',
    criticalEventsNeedAttention: '個關鍵事件需要立即處理。',
    normalOperation: '正常運營',
    noCriticalAlerts: '無關鍵警報。',
    keyIndicators: '關鍵指標',
    indicator: '指標',
    value: '數值',
    overallRiskScore: '整體風險分數',
    environmentalAnomalyCount: '環境異常數',
    routeEventCount: '路線事件數',
    batteryHealthAnalysis: '電池健康分析',
    environmentalMonitoringTitle: '環境監控',
    routeSecurityTitle: '路線安全',
    recommendedActions: '建議行動',
    replaceKeyBatteries: '🔋 立即更換關鍵電池',
    investigateEnvAnomalies: '🌡️ 調查環境異常原因',
    investigateTamper: '🔒 調查篡改警報',
    continueMonitoring: '🔋 持續監控電池健康',
    maintainEnvMonitoring: '🌡️ 維持環境監控',
    continueRouteMonitoring: '🔒 持續路線監控',
    autoGeneratedReport: '此報告由 AI 自動生成',
    
    // Table/List headers
    deviceName: '設備名稱',
    deviceId: '設備 ID',
    valueLabel: '數值',
    threshold: '門檻',
    location: '位置',
    description: '描述',
  },
};

export const t = (key: keyof Translations, lang: Language): string => {
  return translations[lang][key];
};
